config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations",
    sessions: "sessions"}
  resources :users, only: :show

  root "exams#index"

  namespace :admin do
    root "admins#index", as: :root
    resources :subjects, :questions, :users, :exams
    resources :statistic
  end

  namespace :api do
    resources :questions, only: :index
  end

  resources :exams
  get "/:page", to: "static_pages#show"
end

app/models/question.rb
class Question < ApplicationRecord
  acts_as_paranoid
  has_many :results, class_name: Result.name, foreign_key: :question_id
  has_many :answers, class_name: Answer.name, foreign_key: :question_id,
    dependent: :destroy, inverse_of: :question
  belongs_to :user, class_name: User.name
  belongs_to :subject, class_name: Subject.name

  validates :content, presence: true, length: {maximum: Settings.content_size_max}
  accepts_nested_attributes_for :answers, allow_destroy: true,
    reject_if: proc{|attributes| attributes["content"].blank?}
  paginates_per Settings.number_ten

  scope :search, -> content{Question.where("content LIKE ?","%#{content}%")}

  def check_is_correct
    valid = false
    self.answers.each do |ans|
      valid = true if ans.is_correct?
    end
    valid
  end

  def check_answers_quantity
    valid = false
    valid = true if self.answers.size < 6 && self.answers.size > 1
    valid
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  load_and_authorize_resource
  layout "admin"
  before_action :load_subjects, except: [:destroy]

  def index
    @questions = Question.all.page params[:page]
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.check_is_correct && @question.check_answers_quantity &&
      @question.save
      flash[:success] = t ".create_success"
      redirect_to admin_questions_url
    else
      flash[:danger] = t ".fail"
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update_attributes question_params
      flash[:success] = t ".update_success"
      redirect_to admin_questions_url
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find params[:id]
    if @question && @question.destroy
      flash[:success] = t ".destroy_success",
        objects: t("activerecord.model.question")
    else
      flash[:danger] = t ".destroy_error",
        objects: t("activerecord.model.question")
    end
    redirect_to admin_questions_url
  end

  private
  def question_params
    params.require(:question).permit :id, :content, :user_id, :subject_id,
      :status, answers_attributes: [:id, :content, :is_correct]
  end

  def load_subjects
    @subjects = Subject.all
  end
end

app/controllers/api/questions_controller.rb
class Api::QuestionsController < ApplicationController

  def index
    if params[:subject_id].blank?
      @questions = Question.all
    else
      subject = Subject.find_by id: params[:subject_id]
      @questions = subject.questions
    end

    respond_to do |format|
      format.html{render partial: "/admin/questions/questions",
        locals: {questions: @questions}
      }
    end
  end
end

app/views/admin/questions/_answer_fields.html.erb
<div id="answer" class="form-group row">
  <div class="col-md-7">
    <%= f.label :content %>
    <%= f.text_field :content, class: "form-control" %>
  </div>
  <div class="col-md-2">
    <%= f.label :is_correct %> <br>
    <%= f.check_box :is_correct %>
  </div>
  <div class="col-md-2">
    <div class= "remove_fields btn btn-danger">
      <%= link_to_remove_fields t(".remove"), f %>
    </div>
  </div>
</div>

app/views/admin/questions/_form.html.erb
<%= form_for [:admin, @question], html: {multipart: true} do |f| %>
  <div class="form-group">
    <%=  render "shared/error_messages", object: @question %>
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :subject %></br>
        <%= f.select :subject_id, options_for_select(@subjects.collect{
          |subject| [subject.name, subject.id]}), {class: "form-control"} %>
      </div>
      <%= f.hidden_field :user_id, value: current_user.id  %>
      <div class="row">
        <div class="col-md-9">
          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_field :content, class: "form-control", required: "true" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="answer-form">
            <h2 class="text-center new-color"><%= t ".answers" %></h2>
            <div class="form-group">
              <%= f.fields_for :answers do |answers_builder| %>
                <%= render "answer_fields", f: answers_builder %>
              <% end %>
            </div>
            <div class="form-group">
              <div class="btn btn-default add-more-color">
                <%= link_to_add_fields t(".add_more"), f, :answers %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div class="form-group row">
        <div class="offset-sm-2 col-sm-10">
          <%= f.submit t(".save"),
            class: "btn btn-default" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/questions/_questions.html.erb
<div id="questions-list">
  <table class="cart table table-hover new-order">
    <thead>
      <tr class="info row">
        <th class="col-md-1"><%= t ".id" %></th>
        <th class="col-md-2"><%= t ".subject" %></th>
        <th class="col-md-2">
          <span class="product-cart-description">
            <%= t ".content" %>
          </span>
        </th>
        <th class="col-md-1"><%= t ".user_id" %></th>
        <th class="col-md-3"><%= t ".user_name" %></th>
        <th class="col-md-1"><%= t ".status" %></th>
        <th class="col-md-1"></th>
      </tr>
    </thead>
    <tbody>
      <% questions.each do |question|%>
        <tr class="row">
          <td class="col-md-1"><%= question.id %></td>
          <td class="col-md-2">
            <%= question.subject.name %></td>
          <td class="col-md-2"><%= question.content[0..60] %>
            <%= t(".v_v") %></td>
          <td class="col-md-q"><%= question.user_id %></td>
          <% if question.user.present? %>
            <td class="col-md-2"><%= question.user.name %></td>
          <% else %>
            <td class="col-md-2"><%= t ".user_not_exist" %></td>
          <% end %>
          <% if question.status %>
            <td class="col-md-1"><%= t ".active" %></td>
          <% else %>
            <td class="col-md-1"><%= t ".inactive" %></td>
          <% end %>
          <th class="col-md-2 option-product-admin">
            <%= link_to edit_admin_question_path(question),
              class: "btn btn-default button-1" do %>
              <i class="fa fa-wrench"></i>
            <% end %>
            </a>
            <%= link_to admin_question_path(question), method: :delete,
              class: "btn btn-default", data: {confirm: t(".delete_confirm")} do %>
              <span class="fa fa-trash-o"></span>
            <% end %>
          </th>
        </tr>
        <% end %>
        <%= paginate questions %>
    </tbody>
  </table>
</div>

app/views/admin/questions/edit.html.erb
<%= form_for [:admin, @question], html: {multipart: true} do |f| %>
  <div class="form-group">
    <%=  render "shared/error_messages", object: @question %>
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :subject %></br>
        <%= f.select :subject_id, options_for_select(@subjects.collect{
          |subject| [subject.name, subject.id]}), {class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.label :status %> <br>
        <%= f.check_box :status %>
      </div>
      <%= f.hidden_field :user_id, value: current_user.id  %>
      <div class="row">
        <div class="col-md-9">
          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_field :content, class: "form-control", required: "true" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="answer-form">
            <h2 class="text-center new-color"><%= t ".answers" %></h2>
            <div class="form-group">
              <%= f.fields_for :answers do |answers_builder| %>
                <%= render "answer_fields", f: answers_builder %>
              <% end %>
            </div>
            <div class="form-group">
              <div class="btn btn-default add-more-color">
                <%= link_to_add_fields t(".add_more"), f, :answers %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div class="form-group row">
        <div class="offset-sm-2 col-sm-10">
          <%= f.submit t(".save"),
            class: "btn btn-default" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/questions/index.html.erb
<div class="col-md-12 admin-question">
  <div class="row">
    <div class="col-md-4">
      <%= select_tag :subject, options_for_select(@subjects.collect {|c|
        [c.name, c.id]}), {class: "btn subject", id: "subject_select",
        include_blank: t(".subjects")}%>
    </div>
  </div>
  <div class="pull-right btn-add-question">
    <%= link_to "", new_admin_question_path,
      class: "fa fa-plus btn btn-default" %>
  </div>
  <h2 class="text-left"><%= t ".list_questions" %></h2>
  <div id="table-questions">
    <%= render partial: "/admin/questions/questions",
      locals: {questions: @questions} %>
  </div>
</div

app/views/admin/questions/new.html.erb
<div class="col-md-12">
  <%= render "form" %>
</div>