config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations",
    sessions: "sessions"}
  resources :users, only: :show

  root "exams#index"

  namespace :admin do
    root "admins#index", as: :root
    resources :subjects, :questions, :users, :exams
    resources :statistic
  end

  namespace :api do
    resources :questions, only: :index
  end

  resources :exams
  get "/:page", to: "static_pages#show"
end

app/models/exam.rb
class Exam < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  enum status: [:start, :testing, :uncheck, :checked]
  belongs_to :user, class_name: User.name
  belongs_to :subject, class_name: Subject.name
  has_many :results, class_name: Result.name, dependent: :destroy
  has_many :questions, through: :results

  accepts_nested_attributes_for :results

  after_create :create_result
  scope :exams_per_month, -> {
    where(created_at: Time.now.all_month()) }
  scope :score_greater_than, -> score {
    where(created_at: Time.now.all_month()).count
  }
  paginates_per 10

  def caculate_score
    score = 0
    self.results.each do |result|
      unless result.answer.nil?
        score += 1 if result.answer.is_correct?
      end
    end
    score
  end

  def slug_candidates
    [
      [:id, self.subject.name]
    ]
  end

  def self.statistic_score
    scores = Exam.all.map(&:score)
    statistic_score = []
    (0..Subject.maximum(:question_number)).each do |n|
      statistic_score << (Exam.where(score: n).count * 100 / (Exam.count * 1.0)).round(2)
    end
    statistic_score
  end

  private
  def create_result
    subject.questions.where(status: true)
      .sample(subject.question_number).each do |question|
      self.results.create question_id: question.id
    end
  end
end

app/controllers/admin/exams_controller.rb
class Admin::ExamsController < ApplicationController
  load_and_authorize_resource
  layout "admin"

  def index
    @subjects = Subject.all
    @exams = Exam.friendly.order(updated_at: :desc).page params[:page]
  end

  def show
  end

  def update
    params[:score] = @exam.caculate_score
    params[:status] = :checked
    if @exam.update_attributes exam_params
      ResultWorker.perform_async @exam.id
      redirect_to admin_exams_path
    else
      flash[:danger] = t(".update_faild")
      redirect_to admin_exams_path
    end
  end

  private
  def exam_params
    params.permit :status, :score
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  load_and_authorize_resource
  before_action :update_status, only: [:show]

  def index
    @subjects = Subject.all
    @exams = current_user.exams.order(created_at: :desc).page params[:page]
    @exam = Exam.new
  end

  def create
    @exam  = current_user.exams.build exam_params
    if @exam.save
      NoticeWorker.perform_at(Time.zone.now + Settings.delay_time.hours, current_user.id)
      flash[:success] = t ".create_exam_successful"
      redirect_to exams_path
    else
      flash[:danger] = t ".create_faild"
      redirect_to exams_path
    end
  end

  def update
    spent_time = ((Time.now - @exam.updated_at).to_i)*1000
    duration_time = @exam.subject.duration*60*1000
    params[:exam][:spent_time] = spent_time > duration_time ? duration_time : spent_time
    params[:exam][:status] = :uncheck

    if @exam.update_attributes exam_params
      ExamWorker.perform_async
      redirect_to exams_path
    else
      flash[:danger] = t(".update_faild")
      redirect_to exams_path
    end
  end

  def show
  end

  private
  def exam_params
    params.require(:exam).permit :subject_id, :spent_time, :status,
      results_attributes: [:id, :answer_id, :_destroy]
  end

  def update_status
    @exam.update_attributes status: :testing if @exam.start?
  end
end

app/helpers/exam_helper.rb
module ExamHelper
  def format_spent_time spent_time
    s = (spent_time/Settings.one_thousand % Settings.sixty).to_s
    m = (spent_time/Settings.one_thousand/Settings.sixty % Settings.sixty).to_s
    h = (spent_time/(Settings.one_thousand * Settings.sixty * Settings.sixty) %
      Settings.twenty_four).to_s
    time = (t(".zero") + h)[-2..-1] + t(".colon") +
      (t(".zero") + m)[-2..-1] + t(".colon") + (t(".zero") + s)[-2..-1]
  end
end

app/views/exams/index.html.erb
<div class="col-md-12 admin-question">
  <div class="row">
    <div class="col-md-4">
      <%= form_for @exam do |f| %>
        <%= f.select :subject_id, options_for_select(@subjects.collect {|c|
          [c.name, c.id]}), {class: "btn subject", id: "exam-select-subject"}%>
        <%= f.submit t(".create_exam"), class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
  <h2 class="text-left"><%= t ".list_exams" %></h2>
  <div id="table-exams">
    <table class="cart table table-hover new-order">
      <thead>
        <tr class="info row">
          <th class="col-md-2"><%= t ".created_date" %></th>
          <th class="col-md-2"><%= t ".subject" %></th>
          <th class="col-md-2"><%= t ".status" %></th>
          <th class="col-md-1"><%= t ".duration" %></th>
          <th class="col-md-1"><%= t ".question_number" %></th>
          <th class="col-md-1"><%= t ".spent_time" %></th>
          <th class="col-md-1"><%= t ".score" %></th>
          <th class="col-md-2"></th>
        </tr>
      </thead>
      <tbody>
        <% @exams.each do |exam|%>
          <tr class="row">
            <td class="col-md-2">
            <%= exam.created_at.strftime(Settings.format_date) %>
            </td>
            <td class="col-md-2"><%= exam.subject.name %></td>
            <td class="col-md-2"><%= exam.status %></td>
            <td class="col-md-1"><%= exam.subject.duration %></td>
            <td class="col-md-1"><%= exam.subject.question_number %></td>
            <td class="col-md-1">
              <%= format_spent_time exam.spent_time %>
            </td>
            <td class="col-md-1">
            <% unless exam.checked? %>
              <%= t(".no_score") %>
            <% else %>
              <%= exam.score %><%= t(".slash") %><%= exam.subject.question_number %>
            <% end %>
            </td>
            <th class="col-md-2 option-product-admin">
              <% if exam.uncheck? || exam.checked? %>
                <%= link_to exam_path(exam.id), class: "btn btn-default button-1" do %>
                    <i class="fa fa-eye"><%= t ".view" %></i>
                <% end %>
              <% else %>
                <%= link_to exam_path(exam.id), class: "btn btn-default button-1" do %>
                  <i class="fa fa-play"><%= t ".start" %></i>
                <% end %>
              <% end %>
            </th>
          </tr>
        <% end %>
        <%= paginate @exams %>
      </tbody>
    </table>
  </div>
</div

app/views/exams/show.html.erb
<%= javascript_include_tag "timer", "data-turbolinks-track": "load" %>

<div class="row exam">
  <div class="col-md-12">
    <div class="title"><%= @exam.created_at.strftime Settings.format_date %></div>
    <br>
    <h2 class="text-center"><%= @exam.subject.name %></h2>
    <%= hidden_field :exam, :id %>
    <%= hidden_field :exam, :status %>
    <%= hidden_field :exam, :updated_at %>
    <%= hidden_field :subject, :duration, value: @exam.subject.duration %>
    <div id="timer">
      <h4><%= t ".time_remaining" %></h4>

      <span class="hours"></span> :
      <span class="minutes"></span> :
      <span class="seconds"></span>
    </div>
    <hr>
    <div class="question-answer">
      <%= form_for @exam, url: exam_path(@exam.id),
        html: {name: "show_exam"} do |f| %>
        <%= f.fields_for :results do |ff| %>
          <ol>
            <h3><%= ff.object.question.content %></h3>
            <ul>
              <% ff.object.question.answers.each do |ans| %>
              <li>
                <% if @exam.checked? %>
                  <% if ans.is_correct? %>
                    <label class="radio-inline-correct">
                      <%= ff.radio_button :answer_id, ans.id, disabled: true %>
                        <%= ans.content %>
                    </label>
                  <% else %>
                    <label class="radio-inline">
                      <%= ff.radio_button :answer_id, ans.id, disabled: true %>
                        <%= ans.content %>
                    </label>
                  <% end %>
                <% elsif @exam.uncheck? %>
                  <label class="radio-inline">
                    <%= ff.radio_button :answer_id, ans.id, disabled: true %>
                    <%= ans.content %>
                  </label>
                <% else %>
                  <label class="radio-inline">
                    <%= ff.radio_button :answer_id, ans.id %>
                    <%= ans.content %>
                  </label>
                <% end %>
              </li>
              <% end %>
            </ul>
          </ol>
        <% end %>
        <% unless @exam.checked? || @exam.uncheck? %>
          <%= f.submit t(".finish"), method: :update,
            data: {confirm: t(".are_you_sure")}, class: "btn-finish",
            id: "btn_finish" %>
        <% end %>
      <% end %>
    </div>

  </div>
</div>