config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations",
    sessions: "sessions"}
  resources :users, only: :show

  root "exams#index"

  namespace :admin do
    root "admins#index", as: :root
    resources :subjects, :questions, :users, :exams
    resources :statistic
  end

  namespace :api do
    resources :questions, only: :index
  end

  resources :exams
  get "/:page", to: "static_pages#show"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <%= t ".the" %> <a href="http://www.railstutorial.org/"><%= t ".f_exam" %></a>
  <%= t ".by" %> <a href="http://www.michaelhartl.com/"><%= t ".author" %></a>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only"><%= t ".toggle_navigation" %></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <p>
          <%= t ".framgia" %>
        </p>
      </a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="navc"><%= link_to t(".home"), root_path %></li>
        <li class="navc"><%= link_to t(".help"), "/help" %></li>
        <li class="navc"><%= link_to t(".about"), "/about" %></li>
        <% if user_signed_in? %>
          <li class="dropdown navc">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t(".account") %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), user_path(current_user) %></li>
              <li>
                <%= link_to t(".settings"), edit_user_registration_path(current_user) %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".log_out"), destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="navc"><%= link_to t(".login"), new_user_session_path %></li>
        <% end %>
        <li class="navc"><%= link_to t(".signup"), new_user_registration_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t ".admin" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "admin", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "admin", "data-turbolinks-track": true  %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/admin">
            <span><%= t ".admin" %><%= t(".page") %></span>
          </a>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row content-work">
        <div class="sidebar col-md-2">
          <ul id="nav">
            <li>
              <a class="selected" href="/admin">
                <i class="fa fa-dashboard"></i><%= t ".dashboard" %>
              </a>
            </li>
            <li>
              <%= link_to admin_exams_path do %>
                <i class="fa fa-file-text-o"></i>
                <%= t ".list_exams" %>
                <% end %>
            </li>
            <li>
              <%= link_to admin_questions_path do %>
                <i class="fa fa-question-circle"></i>
                <%= t ".question_bank" %>
              <% end %>
            </li>
            <li>
              <a href="#"><i class="fa fa-comment"></i><%= t ".suggestions" %></a>
            </li>
            <li>
              <%= link_to admin_users_path do %>
                <i class="fa fa-user-o"></i>
                <%= t ".users" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-tags"></i>
                <%= t ".subjects" %>
              <% end %>
            </li>
          </ul>
        </div>
        <div class="content col-md-10 col-md-offset-2">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
    <div class="footer container-fluid">

    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "framgia_testing" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: :all,
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag "application",
      "https://fonts.googleapis.com/css?family=Lato:300,300i,400,700,700i,900",
       media: "all", "data-turbolinks-track": true %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container main-body">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>